name: travel_test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  ###
  flutter_bloc: ^8.1.6
  go_router: ^14.1.4
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  intl: ^0.19.0
  flutter_inappwebview: ^5.8.0
  firebase_core: ^2.31.1
  appsflyer_sdk: 
  overlay_support: ^2.1.0
  facebook_app_events: ^0.19.2
  app_tracking_transparency: ^2.0.4
  firebase_remote_config: ^4.4.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  ###
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SFProText-Regular.ttf
    - family: SFProTextMedium
      fonts:
        - asset: assets/fonts/SFProText-Medium.ttf